name: Deploy Salt Infrastructure Management codes
on: 
  pull_request:
      types:
        - closed
      branches:
        - main
        - develop
env:
  TEST_STATES_DIR: /srv/test
  TEST_SALT_ENV: test

jobs:
  deploy:
    name: Deploy Salt States and Salt Pillars
    runs-on: 
      - salt
      - ${{ github.base_ref == 'main' && 'prod' || 'nprod' }}
    if: github.event.pull_request.merged == true
    steps:     
      #- uses: actions/checkout@v3
      - name: Deploy Salt configurations
        run: |
          pwd
          ls -lR