name: Deploy Salt Infrastructure Management codes
on: 
  pull_request:
      types:
        - closed
      branches:
        - main
        - develop
jobs:
  deploy:
    name: Deploy Salt States and Salt Pillars
    runs-on: 
      - salt
      - ${{ github.base_ref == 'main' && 'prod' || 'nprod' }}
    if: github.event.pull_request.merged == true
    steps:     
      - name: Deploy Salt States
        run: sudo rsync -av salt/* /srv/salt/ --delete
      
      - name: Deploy Salt Pillars
        run: sudo rsync -av pillars/* /srv/pillars/ --delete

      - name: Sync Salt resources
        run : sudo salt "*" saltutil.sync_all --async