# teste #
name: salt-infrastructure-management
run-name: Deploying Salt Infrastructure Management
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop
    patchs:
jobs:
  run-if:
    if: github.event.merge == true
    runs-on: salt
    steps:
      - run: uname -a
      
    

