name: salt-infrastructure-management
run-name: Deploying Salt Infrastructure Management
on: 
  pull_request:
      types:
        - opened
      branches:
        - main
        - develop
env:
  TEST_STATES_DIR: /srv/test
  TEST_SALT_ENV: test

jobs:
  test:
    name: Test Salt States and Salt Pillars
    runs-on: 
      - salt
      - ${{ github.base_ref == 'main' && 'prod' || 'nprod' }}
    #if: github.event.pull_request.merged == true
    steps:     
      - uses: actions/checkout@v3

      - name: Install requirements
        run : |
          sudo yum install -y epel-release && \
          sudo yum install -y jq rsync

      - name: Create "test" environment
        run: |
          set -e
          sudo mkdir -p $TEST_STATES_DIR
          sudo rm -rf ${TEST_STATES_DIR}/*
          sudo rsync -av salt/* ${TEST_STATES_DIR}/ --delete
      
      - name: Check Salt States
        run: |
          sudo .github/workflows/scripts/teste-states.sh