name: Validate Salt Infrastructure Management codes
on: 
  pull_request:
      types:
        - opened
      branches:
        - main
        - develop
env:
  STATES_DIR: /srv/validate_salt
  SALT_ENV: validate
  PILLAR_DIR: /srv/pillar/validate_pillar

jobs:
  validate:
    name: Validate Salt States and Salt Pillars
    runs-on: 
      - salt
      - ${{ github.base_ref == 'main' && 'prod' || 'nprod' }}
    steps:     
      - uses: actions/checkout@v3

      - name: Install requirements
        run : |
          sudo yum install -y epel-release && \
          sudo yum install -y jq rsync

      - name: Create "test" environment
        run: |
          set -e
          sudo rm -rf ${STATES_DIR}/* ${PILLAR_DIR}/*
          sudo mkdir -p ${STATES_DIR} ${PILLAR_DIR}
          sudo rsync -av salt/* ${STATES_DIR}/ --delete
          sudo rsync -av pillar/* ${PILLAR_DIR}/ --delete
      
      - name: Check Salt States ans Salt Pillar
        run: |
          sudo .github/workflows/scripts/validate.sh ${STATES_DIR} ${PILLAR_DIR} ${SALT_ENV}

      - name: Remove "test" environment
        run: sudo rm -rf ${STATES_DIR} ${PILLAR_DIR}