name: Validate Salt Infrastructure Management codes
on: 
  pull_request:
      types:
        - opened
      branches:
        - main
        - develop
env:
  TEST_STATES_DIR: /srv/test_salt
  TEST_SALT_ENV: test
  TEST_PILLAR_DIR: /srv/test_pillar

jobs:
  validate:
    name: Validate Salt States and Salt Pillars
    runs-on: 
      - salt
      - ${{ github.base_ref == 'main' && 'prod' || 'nprod' }}
    steps:     
      - uses: actions/checkout@v3

      - name: Install requirements
        run : |
          sudo yum install -y epel-release && \
          sudo yum install -y jq rsync

      - name: Create "test" environment
        run: |
          set -e
          sudo mkdir -p ${TEST_STATES_DIR}
          sudo rm -rf ${TEST_STATES_DIR}/*
          sudo rsync -av salt/* ${TEST_STATES_DIR}/ --delete
      
      - name: Check Salt States ans Salt Pillar
        run: |
          sudo .github/workflows/scripts/validate.sh ${TEST_STATES_DIR} ${TEST_PILLAR_DIR} ${TEST_SALT_ENV}

      - name: Remove "test" environment
        run: sudo rm -rf ${TEST_STATES_DIR}