name: Test States, Pillars and Returner 
on: push
  ##pull_request:
  ##    types:
  ##      - opened
  ##    branches:
  ##      - main
  ##      - develop
env:
  STATES_DIR: /srv/validate_salt
  SALT_ENV: validate
  PILLAR_DIR: /srv/validate_pillar
  PGHOST: 192.168.0.113
  PGDATABASE: postgres
  PGUSER: postgres
  PGPORT: 5432
jobs:
  validate:
    name: Validate Salt States and Salt Pillars
    environment: ${{ github.base_ref == 'main' && 'prod' || 'nprod' }}
    runs-on: 
      - salt
      - ${{ github.base_ref == 'main' && 'prod' || 'nprod' }}
    steps:     
      - uses: actions/checkout@v3

      #- name: Install requirements
      #  run : |
      #    sudo yum install -y epel-release
      #    sudo yum install -y jq rsync snapd
      #    if [[ ! $(snap list yq 2> /dev/null) ]]
      #    then
      #      sudo ln -s /var/lib/snapd/snap /snap
      #      sudo systemctl enable snapd
      #      sudo systemctl start snapd
      #      sudo snap install yq
      #    fi 

      - name: Test access to the Returner database
        run: |
          echo "select count(*) from jids" | psql -h ${PGHOST} -p ${PGPORT} -U ${PGUSER}



      #- name: Create "validate" environment
      #  run: |
      #    set -e
      #    sudo rm -rf ${STATES_DIR}/* ${PILLAR_DIR}/*
      #    sudo mkdir -p ${STATES_DIR} ${PILLAR_DIR}
      #    sudo rsync -av salt/* ${STATES_DIR}/ --delete
      #    sudo rsync -av pillar/* ${PILLAR_DIR}/ --delete
      #
      #- name: Check Salt Pillars and Salt States
      #  run: |
      #    sudo .github/workflows/scripts/validate.sh ${STATES_DIR} ${PILLAR_DIR} ${SALT_ENV}
#
      #- name: Remove "validade" environment
      #  run: sudo rm -rf ${STATES_DIR} ${PILLAR_DIR}